### ISSUE TITLE
Improve comments

### ISSUE THREAD

**Issue by vkaltyrin** [avito-tech/Mixbox#10]
Hey guys, thanks for open-sourcing this repository.

Please consider improving comments. It's hard to understand what does the scheme like a morse code mean :-) 

>
        //
        // test no: 0 1 2 3 4 5 6
        //
        // first    v |   ^ |   ^
        // second     v | | | ^ |
        // third        v | v |

**Comment by artyom-razinov** [comment]
It describes how view is scrolled in this test. It is at "first" view initially (0), it is scrolled from "first" to "second" view (1), then from "second" to "third" view (2), etc.

I'll rewrite comments in English.

**Comment by vkaltyrin** [comment]
I mean notation like this

> v |   ^ |   ^

It would be nice to include some transcript or to remove it completely and just use English words for description. 

Have a good day!
